### ISSUE TITLE
[not really an issue] interesting

### ISSUE THREAD

**Issue by rodrigo1593** [ArcadeMakerSources/ArcadeMaker-Demo#1]
there is any way that you could release your source code? (bc that's how github work, or else, you should put the .zip or the compiled project in release category on the right (?

also i really love it, i do, since i want to stop using game maker and learn something new ;w;

**Comment by ArcadeMakerSources** [comment]
@rodrigo1593 Yeah I will open source it soon, but first I have to prepare the code for this.
And thanks!

**Comment by rodrigo1593** [comment]
im closing this since its not an issue :), when you finish fixing remember to close the issues
