### ISSUE TITLE
[question] how to do soft movement?

### ISSUE THREAD

**Issue by rodrigo1593** [ArcadeMakerSources/ArcadeMaker-Demo#5]
like, im trying to move a rectangle but it moves like it lags or dithering idk, what code i must add to my project to make it work?

**Comment by ArcadeMakerSources** [comment]
Hey again, maybe it's a problem in your code but, as I said in the readme, this demo may have bad performances, but I'm working on silk.net graphics so when it will be ready it's all gonna be much faster and better🙂

**Comment by rodrigo1593** [comment]
im closing this lmao
